FROM node:10

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies (moves package.json and package-lock.json into the Workdir)
COPY package*.json ./

RUN npm install

COPY . .

# Server
EXPOSE 8081

CMD [ "npm", "run", "serve-element:live" ]